export { default as AboutView } from './About'
export { default as DataView } from './Data'
export { default as EditorView } from './Editor'
export { default as ErrorView } from './Error'
export { default as HomeView } from './Home'
export { default as TerminalView } from './Terminal'
